### PR TITLE
Hot Fix #7

### LINKED ISSUE #7: bug: cant upload image twice
1) upload pic
2) click back
3) upload another pic
4) fail :(

### PR DESCRIPTION
**Pull request by AgnitumuS**

### CODE REVIEW

File: packages/demo/src/index.ts [hunk 1]
```diff
@@ -58,7 +58,12 @@ class ImageReader {
 const imageReader = new ImageReader();
 
 dragInput.addEventListener('change', (event) => {
-  imageReader.open((event.target as HTMLInputElement).files);
+    if (event.target && event.target.constructor.name == 'HTMLInputElement'){
+      imageReader.open((event.target as HTMLInputElement).files);
+      event.target.value = "";
+      event.preventDefault();
+      return false;
```
Comment (clbagrat) [inline packages/demo/src/index.ts:65]: i don't think this return is necessary :) 

i'll merge it and then remove it myself
